env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/prometheus/common/version.Version={{.Version}} -X github.com/prometheus/common/version.BuildDate="{{.Date}}" -X github.com/prometheus/common/version.Branch={{.Tag}} -X github.com/prometheus/common/version.Revision={{.FullCommit}} -X github.com/prometheus/common/version.BuildUser="{{.Env.USER}}"

archives:
  -
    name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true
    files:
      - LICENSE
      - NOTICE

checksum:
  name_template: 'sha256sums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

dockers:
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - '--label=org.label-schema.schema-version=1.0'
      - '--label=org.label-schema.version={{.Version}}'
      - '--label=org.label-schema.name={{.ProjectName}}'
    image_templates:
      - 'ghcr.io/zebbra/iperf3-exporter:{{ .Tag }}-amd64'
    goos: linux
    goarch: amd64
    ids:
      - iperf3-exporter
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
      - '--label=org.label-schema.schema-version=1.0'
      - '--label=org.label-schema.version={{.Version}}'
      - '--label=org.label-schema.name={{.ProjectName}}'
    image_templates:
      - 'ghcr.io/zebbra/iperf3-exporter:{{ .Tag }}-arm64'
    goos: linux
    goarch: arm64
    ids:
      - iperf3-exporter
docker_manifests:
  - name_template: ghcr.io/zebbra/iperf3-exporter:{{ .Tag }}
    image_templates:
      - "ghcr.io/zebbra/iperf3-exporter:{{ .Tag }}-amd64"
      - "ghcr.io/zebbra/iperf3-exporter:{{ .Tag }}-arm64"
  - name_template: ghcr.io/zebbra/iperf3-exporter:latest
    image_templates:
      - "ghcr.io/zebbra/iperf3-exporter:{{ .Tag }}-amd64"
      - "ghcr.io/zebbra/iperf3-exporter:{{ .Tag }}-arm64"
